sudo: required
services:
  - docker


before_install:
  - docker build -t nolascoacosta/docker-react -f Dockerfile.dev .  

script:
  - docker -it run nolascoacosta/docker-react npm run test -- --coverage